name: Weekly Calendar Update

on:
  schedule:
    # Runs every Sunday at 8 PM Singapore time (12 PM UTC)
    # This sends updates to all configured groups
    - cron: '0 12 * * 0'
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  send-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Send weekly calendar updates to groups
      env:
        # Telegram Configuration
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        ADMIN_USER_ID: ${{ secrets.ADMIN_USER_ID }}
        
        # Google Calendar - Service Account Authentication
        GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        GOOGLE_CALENDAR_OWNER_EMAIL: ${{ secrets.GOOGLE_CALENDAR_OWNER_EMAIL }}
        
        # Multi-Group Configuration (Base64 encoded JSON)
        GROUP_CALENDAR_MAPPINGS: ${{ secrets.GROUP_CALENDAR_MAPPINGS }}
        
        # Global Settings
        CALENDAR_ID: ${{ secrets.CALENDAR_ID }}
        TIMEZONE: ${{ secrets.TIMEZONE }}
      run: |
        echo "🤖 Starting Schedule Nudge Bot weekly update..."
        echo "📅 Configured timezone: ${TIMEZONE}"
        npm start
        echo "✅ Weekly update process completed"