name: Weekly Calendar Update

on:
  schedule:
    # Runs every Sunday at 8 PM UTC (adjust timezone as needed)
    # Format: minute hour day month day-of-week
    # 0 12 * * 0 = every Sunday at 6 PM
    - cron: '0 12 * * 0'
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  send-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Send weekly calendar update
      env:
        # Telegram Configuration
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        ALLOWED_USER_IDS: ${{ secrets.ALLOWED_USER_IDS }}
        ADMIN_USER_ID: ${{ secrets.ADMIN_USER_ID }}
        
        # Google Calendar - Service Account
        GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        GOOGLE_CALENDAR_OWNER_EMAIL: ${{ secrets.GOOGLE_CALENDAR_OWNER_EMAIL }}
        
        # Calendar Settings
        CALENDAR_ID: ${{ secrets.CALENDAR_ID }}
        TIMEZONE: ${{ secrets.TIMEZONE }}
      run: npm start