name: Weekly Calendar Update

on:
  schedule:
    # Runs every Sunday at 6 PM UTC (adjust timezone as needed)
    # Format: minute hour day month day-of-week
    # 0 18 * * 0 = every Sunday at 6 PM
    - cron: '0 18 * * 0'
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  send-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Send weekly calendar update
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
        GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
        CALENDAR_ID: ${{ secrets.CALENDAR_ID }}
        TIMEZONE: ${{ secrets.TIMEZONE }}
      run: npm start